### ISSUE TITLE
load and display metric map

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/ToNE#3]
You need to set the background of your editor from an actual metric map. @jailander to provide one...
Also read the YAML information to be able to transform pixel coordinates into metric map coordinates

**Comment by marc-hanheide** [comment]
you need to look at the [YAML definition](http://wiki.ros.org/map_server#YAML_format) of the map to find out resolution and origin of the map. This needs to be loadable via menu or tool button.

**Comment by marc-hanheide** [comment]
load yaml like this:

``` python
with open("/home/lcas/Downloads/arena.yaml", 'r') as stream:
     print(yaml.load(stream))
```

This will return a structure like this:

``` json
{'free_thresh': 0.196,
 'image': 'arena.pgm',
 'negate': 0,
 'occupied_thresh': 0.65,
 'origin': [-5.199999999999989, -5.1499999999999915, 0.0],
 'resolution': 0.05}
```

Then load the image map that is given there as `QPixmap`

**Comment by marc-hanheide** [comment]
take #7 as inspiration.

**Comment by Laxnyama** [comment]
QPixmap was not loading the so i had to use QImage  to load the image which allows for more properties of the object to be accessed e.g size but still trying to figure out how to access these properties so i can try convert the pixels into metrics

**Comment by Jailander** [comment]
This is done
